### ISSUE TITLE
Update cloud foundry sample manifest

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry-attic/cf-docs#157]
The example posted is about 4 months old: https://github.com/cloudfoundry/cf-docs/blob/master/source/docs/running/deploying-cf/vsphere/cloud-foundry-example-manifest.md

I'm trying to update manifest properties for the latest code and an up to date example would be really helpful. In fact, can this be automatically generated as a part of CI?

**Comment by andypiper** [comment]
This page still refers to `uaa.cloudfoundry.com` too - customer reported this to me and wanted to know whether it is intentional?

```
   vmc:
        override: true
        authorized-grant-types: implicit
        authorities: uaa.none
        redirect-uri: http://uaa.cloudfoundry.com/redirect/vmc,https://uaa.cloudfoundry.com/redirect/vmc
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
```
